services:
  airflow-webserver:
    build:
      context: .
      dockerfile: webserver.Dockerfile
    container_name: airflow-webserver
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

      AIRFLOW_ADMIN_USERNAME: admin
      AIRFLOW_ADMIN_FIRSTNAME: Admin
      AIRFLOW_ADMIN_LASTNAME: User
      AIRFLOW_ADMIN_EMAIL: admin@example.com
      AIRFLOW_ADMIN_PASSWORD: password

    ports:
      - "8088:8080"
    restart: always
    networks:
      - default

networks:
  default:
    name: airflow_network
