services:
  postgres-service:
    build:
      context: .
      dockerfile: postgres.Dockerfile
      args:
        USER_ID: ${HOST_UID}
        GROUP_ID: ${HOST_GID}
    container_name: postgres-service-db
    ports:
      - "5422:5432"
    volumes:
      - postgres_data:/var/lib/pgsql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow
networks:
  default:
    name: postgres_network

volumes:
  postgres_data:
