services:
  airflow-worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
      args:
        GLOBAL_CERT: ${GLOBAL_CERT}
        GLOBAL_INDEX: ${GLOBAL_INDEX}
        GLOBAL_INDEX_URL: ${GLOBAL_INDEX_URL}
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    container_name: airflow-worker
    tmpfs:
      - /home/airflow/airflow/cloned_repositories:size=20G,mode=1777,exec
      - /home/airflow/airflow/logs:size=500M,mode=1777,uid=${HOST_UID},gid=${HOST_GID},exec
      - /home/airflow/airflow/output:size=500M,mode=1777,exec
    environment:
      WORKER_QUEUE: ${WORKER_QUEUE}  # No default - will fail if not provided
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__BROKER_URL: redis://192.168.1.188:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
      RULESET_MAPPING_FILE: ${RULESET_MAPPING_FILE}
      METRICS_DATABASE_USER: ${METRICS_DATABASE_USER}
      METRICS_DATABASE_PASSWORD: ${METRICS_DATABASE_PASSWORD}
      METRICS_DATABASE_HOST: ${METRICS_DATABASE_HOST}
      METRICS_DATABASE_PORT: ${METRICS_DATABASE_PORT}
      METRICS_DATABASE_NAME: ${METRICS_DATABASE_NAME}
      TRIVYIGNORE_TEMPLATE: ${TRIVYIGNORE_TEMPLATE}
      SYFT_CONFIG_PATH: ${SYFT_CONFIG_PATH}
      GRYPE_CONFIG_PATH: ${GRYPE_CONFIG_PATH}
      SEMGREP_CONFIG_DIR: ${SEMGREP_CONFIG_DIR}
      BITBUCKET_HOSTNAME: ${BITBUCKET_HOSTNAME}
      GITLAB_HOSTNAME: ${GITLAB_HOSTNAME}
      KANTRA_RULESETS: ${KANTRA_RULESETS}
      KANTRA_OUTPUT_ROOT: /home/airflow/airflow/output
      HTTP_PROXY_HOST: "${HTTP_PROXY_HOST:-}"
      HTTP_PROXY_PORT: "${HTTP_PROXY_PORT:-}"
      HTTP_PROXY_USER: "${HTTP_PROXY_USER:-}"
      HTTP_PROXY_PASSWORD: "${HTTP_PROXY_PASSWORD:-}"
      TRUSTSTORE_PATH: "${TRUSTSTORE_PATH:-}"
      TRUSTSTORE_PASSWORD: "${TRUSTSTORE_PASSWORD:-}"
      DEFAULT_PROCESS_TIMEOUT: ${DEFAULT_PROCESS_TIMEOUT}
    command: ["${WORKER_QUEUE}"]  # Fixed variable substitution
    restart: always
    volumes:
      - ${SSH_KEYS_PATH}:/tmp/keys/id_ed25519:ro,Z
      - ${SSH_KEYS_PUB_PATH}:/tmp/keys/id_ed25519.pub:ro,Z
      - ${SSH_KNOWN_HOSTS_PATH}:/tmp/keys/known_hosts:ro,Z
      - ${USER_HOME}/java.cacerts:/tmp/keys/java.cacerts:ro,Z
      - ${GRADLE_CACHE_PATH}:/home/airflow/.gradle
      - ${M2_CACHE_PATH}:/home/airflow/.m2
    networks:
      - worker_network

networks:
  worker_network:
    name: worker_network
    ##external: true
