categories:
  - name: "Database & Persistence"
    patterns:
      - ".*mongoose.*"
      - ".*sequelize.*"
      - ".*knex.*"
      - ".*typeorm.*"
      - ".*pg.*"
      - ".*mysql.*"
      - ".*sqlite.*"
      - ".*leveldb.*"
  - name: "Messaging & Event Streaming"
    patterns:
      - ".*kafkajs.*"
      - ".*rabbitmq.*"
      - ".*amqplib.*"
      - ".*nats.*"
      - ".*bull.*"
      - ".*agenda.*"
  - name: "Web & Application Frameworks"
    patterns:
      - ".*express.*"
      - ".*koa.*"
      - ".*hapi.*"
      - ".*fastify.*"
      - ".*sails.*"
      - ".*meteor.*"
      - ".*next.*"
      - ".*nuxt.*"
  - name: "Application Servers & Runtime Containers"
    patterns:
      - ".*pm2.*"
      - ".*forever.*"
      - ".*nodemon.*"
  - name: "Security & Authentication"
    patterns:
      - ".*jsonwebtoken.*"
      - ".*passport.*"
      - ".*bcrypt.*"
      - ".*argon2.*"
      - ".*helmet.*"
  - name: "Caching & In-Memory Data Stores"
    patterns:
      - ".*node-cache.*"
      - ".*memory-cache.*"
      - ".*redis.*"
  - name: "Logging, Monitoring & Observability"
    patterns:
      - ".*winston.*"
      - ".*pino.*"
      - ".*morgan.*"
      - ".*log4js.*"
      - ".*prom-client.*"
      - ".*sentry.*"
  - name: "Testing, Quality Assurance & Mocking"
    patterns:
      - ".*jest.*"
      - ".*mocha.*"
      - ".*chai.*"
      - ".*ava.*"
      - ".*cypress.*"
      - ".*supertest.*"
      - ".*sinon.*"
  - name: "Cloud, Containerization & Orchestration"
    patterns:
      - ".*aws-sdk.*"
      - ".*google-cloud.*"
      - ".*azure.*"
      - ".*firebase.*"
      - ".*docker.*"
      - ".*kubernetes.*"
  - name: "Build, Dependency Management & Deployment Tools"
    patterns:
      - ".*webpack.*"
      - ".*gulp.*"
      - ".*grunt.*"
      - ".*rollup.*"
      - ".*esbuild.*"
      - ".*babel.*"
      - ".*lerna.*"
      - ".*nx.*"
  - name: "Data Serialization, Transformation & Processing"
    patterns:
      - ".*csv-parser.*"
      - ".*papaparse.*"
      - ".*jsonschema.*"
      - ".*protobuf.*"
  - name: "Networking & Communication"
    patterns:
      - ".*axios.*"
      - ".*node-fetch.*"
      - ".*superagent.*"
      - ".*request.*"
      - ".*websocket.*"
      - ".*ws.*"
  - name: "Utility & Helper Libraries"
    patterns:
      - ".*lodash.*"
      - ".*underscore.*"
      - ".*moment.*"
      - ".*date-fns.*"
      - ".*ramda.*"
  - name: "User Interface & Client-Side"
    patterns:
      - ".*react.*"
      - ".*angular.*"
      - ".*vue.*"
      - ".*svelte.*"
      - ".*ember.*"
      - ".*jquery.*"
      - ".*bootstrap.*"
      - ".*tailwind.*"
  - name: "Documentation, Code Generation & Development Tools"
    patterns:
      - ".*jsdoc.*"
      - ".*typedoc.*"
      - ".*eslint.*"
      - ".*prettier.*"
      - ".*husky.*"
      - ".*lint-staged.*"
  - name: "Analytics, Machine Learning & Big Data"
    patterns:
      - ".*brain.js.*"
      - ".*tensorflow.*"
      - ".*onnx.*"
      - ".*pandas-js.*"
      - ".*apache-arrow.*"