base:
  fetch_repos: flows.tasks.base_tasks.fetch_repositories_task
  clone: flows.tasks.base_tasks.clone_repository_task
  cleanup: flows.tasks.base_tasks.cleanup_repo_task
  start: flows.tasks.base_tasks.start_task
  update_status: flows.tasks.base_tasks.update_status_task
  refresh_views: flows.tasks.base_tasks.refresh_views_task

core:
  checkov: flows.tasks.core_tasks.run_checkov_analysis_task
  semgrep: flows.tasks.core_tasks.run_semgrep_analysis_task
  trivy: flows.tasks.core_tasks.run_trivy_analysis_task
  syft: flows.tasks.core_tasks.run_syft_analysis_task
  grype: flows.tasks.core_tasks.run_grype_analysis_task
  xeol: flows.tasks.core_tasks.run_xeol_analysis_task
  lizard: flows.tasks.core_tasks.run_lizard_task
  cloc: flows.tasks.core_tasks.run_cloc_task
  category: flows.tasks.core_tasks.run_catgeory_analysis_task
  gitlog: flows.tasks.core_tasks.run_gitlog_task
  goenry: flows.tasks.core_tasks.run_goenry_task
  syft_dependency: flows.tasks.core_tasks.run_syft_dependency_analysis_task
  iac_components: flows.tasks.core_tasks.run_iac_component_analysis_task

languages:
  go:
    build: flows.tasks.go_tasks.run_go_build_tool_task
    dependencies: flows.tasks.go_tasks.run_go_dependency_task
  java:
    gradle:
      build: flows.tasks.java_tasks.run_gradlejdk_task
      dependencies: flows.tasks.java_tasks.run_gradle_dependency_task
    maven:
      build: flows.tasks.java_tasks.run_mavenjdk_task
      dependencies: flows.tasks.java_tasks.run_maven_dependency_task
  javascript:
    build: flows.tasks.javascript_tasks.run_javascript_build_tool_task
    dependencies: flows.tasks.javascript_tasks.run_javascript_dependency_task
  python:
    build: flows.tasks.python_tasks.run_python_build_tool_task
    dependencies: flows.tasks.python_tasks.run_python_dependency_task
