databases:
  - name: postgres_migration
    source_type: postgres
    enabled: true
    source_db: postgresql://postgres:postgres@192.168.1.188:5432/gitlab%2Dusage
    target_db: postgresql://postgres:postgres@localhost/gitlab%2Dusage
    tables:
      - source: public.dependencies
        dest: public.dependencies_temp
        enabled: true

  - name: sqlserver_migration
    source_type: sqlserver
    enabled: false
    source_db: "DSN=sqlserver_source"
    target_db: postgresql://postgres:postgres@localhost/gitlab%2Dusage
    tables:
      - source: dbo.syft_dependencies
        dest: public.syft_dependencies_temp
        enabled: true