# tasks/registry/task_registry.yaml
base:
  # Repository operations
  fetch_repos: tasks.base_tasks.fetch_repositories_task
  clone: tasks.base_tasks.clone_repository_task
  cleanup: tasks.base_tasks.cleanup_repo_task
  
  # Flow management
  start: tasks.base_tasks.start_task
  update_status: tasks.base_tasks.update_status_task
  refresh_views: tasks.base_tasks.refresh_views_task
  
  # Initialization/Reporting
  initialize: tasks.base_tasks.initialize_environment_task
  final_report: tasks.base_tasks.generate_final_report_task
  notify: tasks.base_tasks.send_notification_task

core:
  # Security analysis
  checkov: tasks.core_tasks.run_checkov_analysis_task
  semgrep: tasks.core_tasks.run_semgrep_analysis_task
  trivy: tasks.core_tasks.run_trivy_analysis_task
  syft: tasks.core_tasks.run_syft_analysis_task
  grype: tasks.core_tasks.run_grype_analysis_task
  xeol: tasks.core_tasks.run_xeol_analysis_task
  
  # Code metrics
  lizard: tasks.core_tasks.run_lizard_task
  cloc: tasks.core_tasks.run_cloc_task
  category: tasks.core_tasks.run_catgeory_analysis_task
  gitlog: tasks.core_tasks.run_gitlog_task

languages:
  # Go
  go:
    build: tasks.go_tasks.run_go_build_tool_task
    dependencies: tasks.go_tasks.run_go_dependencies_task
  
  # Java
  java:
    gradle:
      build: tasks.java_tasks.run_gradlejdk_task
      dependencies: tasks.java_tasks.run_gradle_dependencies_task
    maven:
      build: tasks.java_tasks.run_mavenjdk_task
      dependencies: tasks.java_tasks.run_maven_dependencies_task
  
  # JavaScript
  javascript:
    build: tasks.javascript_tasks.run_javascript_build_tool_task
    dependencies: tasks.javascript_tasks.run_javascript_dependencies_task
  
  # Python
  python:
    build: tasks.python_tasks.run_python_build_tool_task
    dependencies: tasks.python_tasks.run_python_dependencies_task
