categories:
  - name: "Database & Persistence"
    patterns:
      - ".*sqlalchemy.*"
      - ".*psycopg2.*"
      - ".*mysqlclient.*"
      - ".*pymongo.*"
      - ".*cassandra-driver.*"
  - name: "Messaging & Event Streaming"
    patterns:
      - ".*kafka.*"
      - ".*rabbitmq.*"
      - ".*celery.*"
      - ".*kombu.*"
  - name: "Web & Application Frameworks"
    patterns:
      - ".*django.*"
      - ".*flask.*"
      - ".*fastapi.*"
      - ".*tornado.*"
      - ".*pyramid.*"
  - name: "Application Servers & Runtime Containers"
    patterns:
      - ".*gunicorn.*"
      - ".*uwsgi.*"
      - ".*waitress.*"
  - name: "Security & Authentication"
    patterns:
      - ".*authlib.*"
      - ".*pyjwt.*"
      - ".*bcrypt.*"
      - ".*passlib.*"
  - name: "Caching & In-Memory Data Stores"
    patterns:
      - ".*redis.*"
      - ".*memcached.*"
      - ".*pylibmc.*"
      - ".*dogpile\\.cache.*"
  - name: "Logging, Monitoring & Observability"
    patterns:
      - ".*loguru.*"
      - ".*structlog.*"
      - ".*sentry.*"
      - ".*prometheus_client.*"
  - name: "Testing, Quality Assurance & Mocking"
    patterns:
      - ".*pytest.*"
      - ".*nose.*"
      - ".*unittest.*"
      - ".*tox.*"
      - ".*hypothesis.*"
  - name: "Cloud, Containerization & Orchestration"
    patterns:
      - ".*boto3.*"
      - ".*google-cloud.*"
      - ".*azure.*"
      - ".*docker.*"
      - ".*kubernetes.*"
  - name: "Build, Dependency Management & Deployment Tools"
    patterns:
      - ".*pip.*"
      - ".*setuptools.*"
      - ".*wheel.*"
      - ".*poetry.*"
      - ".*flit.*"
  - name: "Data Serialization, Transformation & Processing"
    patterns:
      - ".*pandas.*"
      - ".*numpy.*"
      - ".*pyyaml.*"
      - ".*jsonschema.*"
      - ".*xmltodict.*"
  - name: "Networking & Communication"
    patterns:
      - ".*requests.*"
      - ".*httpx.*"
      - ".*urllib3.*"
      - ".*aiohttp.*"
  - name: "Utility & Helper Libraries"
    patterns:
      - ".*python-dateutil.*"
      - ".*click.*"
      - ".*pytz.*"
      - ".*toolz.*"
      - ".*boltons.*"
  - name: "User Interface & Client-Side"
    patterns:
      - ".*tkinter.*"
      - ".*pyqt.*"
      - ".*kivy.*"
      - ".*wxpython.*"
  - name: "Documentation, Code Generation & Development Tools"
    patterns:
      - ".*sphinx.*"
      - ".*mkdocs.*"
      - ".*pdoc.*"
      - ".*black.*"
      - ".*isort.*"
  - name: "Analytics, Machine Learning & Big Data"
    patterns:
      - ".*scikit-learn.*"
      - ".*tensorflow.*"
      - ".*keras.*"
      - ".*pytorch.*"
      - ".*dask.*"
      - ".*pyspark.*"
      - ".*xgboost.*"
      - ".*lightgbm.*"