categories:
  - name: "Data Management & Storage"
    subcategories:
      - name: "NoSQL & Big Data"
        patterns:
          - "^org\\.apache\\.(hbase|hive|flume|accumulo|omid|oozie|nifi|solr|lucene|derby|parquet|phoenix|pig|spark|sqoop|tez):.*"
          - "^org\\.apache\\.cassandra:.*"
          - "^org\\.apache\\.hadoop:.*"

      - name: "Relational Databases"
        patterns:
          - "^org\\.apache\\.(ibatis|openjpa|sqoop):.*"

  - name: "Security & Identity"
    subcategories:
      - name: "Authentication"
        patterns:
          - "^org\\.apache\\.(kerby|shiro):.*"
      - name: "Authorization & Access Control"
        patterns:
          - "^org\\.apache\\.(ranger|sentry):.*"
      - name: "Security Layers"
        patterns:
          - "^org\\.apache\\.bcel:.*"
      - name: "Identity Management"
        patterns:
          - "^org\\.apache\\.(directory|oltu):.*"

  - name: "Application Development"
    subcategories:
      - name: "Web Frameworks"
        patterns:
          - "^org\\.apache\\.(click|cocoon|myfaces|wicket|causeway|sling|struts|taglibs|tuscany):.*"
      - name: "Template Engines"
        patterns:
          - "^org\\.apache\\.(velocity|tiles):.*"
      - name: "Dependency Injection"
        patterns:
          - "^org\\.apache\\.xbean:.*"

  - name: "Serialization"
    subcategories:
      - name: "JSON/XML"
        patterns:
          - "^org\\.apache\\.(axiom|xmlbeans|abdera|johnzon|xmlgraphics|xalan|xerces|XML|xmlrpc):.*"
      - name: "Protocol Buffers & Binary Formats"
        patterns:
          - "^org\\.apache\\.thrift:.*"

  - name: "Messaging & Data Integration"
    subcategories:
      - name: "Message Brokers & ETL Tools"
        patterns:
          - "^org\\.apache\\.(activemq|camel):.*"
      - name: "Networking"
        patterns:
          - "^org\\.apache\\.(mina|ftpserver|ssh):.*"

  - name: "Utilities & Libraries"
    subcategories:
      - name: "General-Purpose"
        patterns:
          - "^(org\\.apache\\.)?commons:.*"
          - "^org\\.apache\\.(lang3|codec|jackrabbit|any23|curator|methi|poi|opennlp|pdfbox|tika|wooden|sls|zookeeper):.*"
          - "^com\\.google\\.(guava|code\\..*):.*"
          - "^org\\.codehaus\\.groovy:.*"
