categories:
  - name: "Application Development"

    subcategories:

      - name: "Web Frameworks"
        patterns:
          - "io\\.ktor.*"
          - "gg\\.jte.*"
          - "io\\.searchbox.*"
          - "io\\.specto.*"
          - "org\\.grails.*"

      - name: "Reactive Libraries"
        patterns:
          - "io\\.projectreactor.*"
          - "io\\.projectreactor\\.(spring|kafka|netty|addons).*"
          - "io\\.reactivex\\.(rxjava2|rxjava3).*"
          - "io\\.vertx.*"
          - "org\\.reactivesteams.*"

      - name: "Dependency Injection"
        patterns:
          - "io\\.micronaut:micronaut-spring"

      - name: "Template Engines"
        patterns:
          - "org\\.apache\\.velocity.*"
          - "com\\.querydsl.*"
          - "org\\.freemarker.*"
          - "org\\.thymeleaf\\.extras.*"
          - "org\\.springdoc.*"
