categories:
  - name: "Data Management & Storage"
    subcategories:
      - name: "Relational Databases"
        patterns:
          - "com\\.h2database.*"
          - "com\\.ibm\\.db2.*"
          - "com\\.microsoft\\.sqlserver.*"
          - "com\\.mysql.*"
          - "com\\.oracle\\.(jdbc|ojdbc|database).*"
          - "commons-dbcp.*"
          - "com\\.zaxxer.*"
          - "commons-pool.*"
          - "io\\.r2dbc.*"
          - "net\\.sourceforge\\.jtds.*"
          - "mysql.*"
          - "org\\.flywaydb.*"
          - "org\\.firebirdsql\\.jdbc.*"
          - "org\\.hibernate\\.(orm|validator).*"
          - "org\\.hsqldb.*"
          - "org\\.jooq.*"
          - "org\\.liquibase.*"
          - "org\\.mariadb.*"
          - "org\\.postgresql.*"
          - "org\\.xerial.*"
          - "com\\.oracle\\..*"
          - "io\\.r2dbc.*"
          - "com\\.querydsl.*"
          - "org\\.flywaydb.*"

      - name: "NoSQL & Big Data"
        patterns:
          - "com\\.couchbase\\.client.*"
          - "com\\.datastax\\.(cassandra|oss).*"
          - "co\\.elastic\\.clients.*"
          - "com\\.oracle\\.coherence.*"
          - "io\\.lettuce.*"
          - "org\\.influxdb.*"
          - "org\\.mongodb.*"
          - "org\\.neo4j.*"
          - "redis\\.clients\\.*"
          - "org\\.elasticsearch\\.client.*"

      - name: "Caching"
        patterns:
          - "com\\.hazelcast.*"
          - "net\\.sf\\.encache.*"
          - "org\\.cache2k.*"
          - "org\\.ehcache.*"
          - "org\\.infinispan.*"
          - "com\\.github\\.ben-manes.*"


