categories:
  - name: "Infrastructure & Deployment"
    subcategories:
      - name: "Application Servers"
        patterns:
          - "^jakarta\\.ejb(\\..*)?:.+$"
          - "^jakarta\\.ejb\\.embeddable(\\..*)?:.+$"
          - "^jakarta\\.ejb\\.spi(\\..*)?:.+$"
          - "^jakarta\\.resource(\\..*)?:.+$"
          - "^jakarta\\.batch(\\..*)?:.+$"

  - name: "Data Management & Storage"
    subcategories:
      - name: "Relational Databases"
        patterns:
          - "^jakarta\\.persistence(\\..*)?:.+$"
          - "^jakarta\\.transaction(\\..*)?:.+$"
      - name: "NoSQL & Big Data"
        patterns: []
      - name: "Caching"
        patterns: []
      - name: "Data Lakes & Analytics"
        patterns: []

  - name: "Messaging & Data Integration"
    subcategories:
      - name: "Message Brokers & ETL Tools"
        patterns:
          - "^jakarta\\.jms(\\..*)?:.+$"
          - "^jakarta\\.mail(\\..*)?:.+$"
      - name: "API Gateways & REST/GraphQL"
        patterns:
          - "^jakarta\\.ws\\.rs(\\..*)?:.+$"
          - "^jakarta\\.jws(\\..*)?:.+$"
          - "^jakarta\\.xml\\.ws(\\..*)?:.+$"
          - "^jakarta\\.xml\\.soap(\\..*)?:.+$"
      - name: "Event Streaming"
        patterns: []
      - name: "Networking"
        patterns: []

  - name: "Application Development"
    subcategories:
      - name: "Web Frameworks"
        patterns:
          - "^jakarta\\.faces(\\..*)?:.+$"
          - "^jakarta\\.servlet(\\..*)?:.+$"
          - "^jakarta\\.el(\\..*)?:.+$"
          - "^jakarta\\.websocket(\\..*)?:.+$"
      - name: "Spring: Boot"
        patterns: []
      - name: "Spring: Framework"
        patterns: []
      - name: "Reactive Libraries"
        patterns: []
      - name: "Dependency Injection"
        patterns:
          - "^jakarta\\.enterprise\\.inject(\\..*)?:.+$"
          - "^jakarta\\.inject(\\..*)?:.+$"
          - "^jakarta\\.enterprise\\.context(\\..*)?:.+$"
          - "^jakarta\\.enterprise\\.event(\\..*)?:.+$"
          - "^jakarta\\.enterprise\\.concurrent(\\..*)?:.+$"
          - "^jakarta\\.interceptor(\\..*)?:.+$"
          - "^jakarta\\.decorator(\\..*)?:.+$"
          - "^jakarta\\.enterprise\\.util(\\..*)?:.+$"
      - name: "Template Engines"
        patterns: []

  - name: "Serialization"
    subcategories:
      - name: "JSON/XML"
        patterns:
          - "^jakarta\\.json(\\..*)?:.+$"
          - "^jakarta\\.json\\.bind(\\..*)?:.+$"
          - "^jakarta\\.json\\.spi(\\..*)?:.+$"
          - "^jakarta\\.json\\.stream(\\..*)?:.+$"
          - "^jakarta\\.xml\\.bind(\\..*)?:.+$"
      - name: "Protocol Buffers & Binary Formats"
        patterns: []

  - name: "Security & Identity"
    subcategories:
      - name: "Authentication"
        patterns:
          - "^jakarta\\.security\\.auth\\.message(\\..*)?:.+$"
          - "^jakarta\\.annotation\\.security(\\..*)?:.+$"
      - name: "Security Layers"
        patterns:
          - "^jakarta\\.security\\.jacc(\\..*)?:.+$"
      - name: "Transport & Data Security "
        patterns:
          - "^jakarta\\.security\\.enterprise\\.authentication\\.mechanism\\.http(\\..*)?:.+$"
      - name: "Identity Management"
        patterns:
          - "^jakarta\\.security\\.enterprise\\.credential(\\..*)?:.+$"
          - "^jakarta\\.security\\.enterprise\\.identitystore(\\..*)?:.+$"
          - "^jakarta\\.security\\.enterprise(\\..*)?:.+$"

  - name: "Observability & Reliability"
    subcategories:
      - name: "Logging & Monitoring"
        patterns: []
      - name: "Metrics & Distributed Tracing"
        patterns: []
      - name: "Circuit Breakers & Rate Limiting"
        patterns: []

  - name: "Development & Testing Tools"
    subcategories:
      - name: "Build Tools & Dependency Management"
        patterns: []
      - name: "Testing"
        patterns: []
      - name: "Code Quality & Profiling"
        patterns: []

  - name: "Utilities & Libraries"
    subcategories:
      - name: "General-Purpose"
        patterns:
          - "^jakarta\\.activation(\\..*)?:.+$"
          - "^jakarta\\.annotation(\\..*)?:.+$"
          - "^jakarta\\.annotation\\.sql(\\..*)?:.+$"
          - "^jakarta\\.validation(\\..*)?:.+$"
