categories:

  - name: "Infrastructure & Deployment"
    subcategories:

      - name: "Application Servers"
        patterns:
          - "(javax|jakarta)\\.(ejb|management|concurrency|connector|resource)\\..*"


  - name: "Data Management & Storage"
    subcategories:

      - name: "Relational Databases"
        patterns:
          - "(javax|jakarta)\\.(persistence|transaction)\\..*"

      - name: "NoSQL & Big Data"
        patterns:
          - "jakarta\\.nosql\\..*"
          - "(javax|jakarta)\\.jms\\..*"


  - name: "Messaging & Data Integration"
    subcategories:

      - name: "Message Brokers & ETL Tools"
        patterns:
          - "(javax|jakarta)\\.jms\\..*"
          - "javax\\.batch\\..*"

      - name: "API Gateways & REST/GraphQL"
        patterns:
          - "(javax|jakarta)\\.ws\\.(rs|soap|xml\\.ws)\\..*"
          - "jakarta\\.rest\\..*"


  - name: "Application Development"
    subcategories:

      - name: "Web Frameworks"
        patterns:
          - "(javax|jakarta)\\.(faces|servlet\\.jsp|websocket)\\..*"

      - name: "Dependency Injection"
        patterns:
          - "(javax|jakarta)\\.(inject|enterprise|interceptors|decorator)\\..*"

      - name: "Reactive Libraries"
        patterns:
          - "jakarta\\.reactive\\..*"


  - name: "Serialization"
    subcategories:

      - name: "JSON/XML"
        patterns:
          - "(javax|jakarta)\\.(json|xml\\.bind)\\..*"
          - "(javax|jakarta)\\.(el|validation|activation|xml\\.parsers)\\..*"

      - name: "Protocol Buffers & Binary Formats"
        patterns:
          - "jakarta\\.protobuf\\..*"


  - name: "Security & Identity"
    subcategories:

      - name: "Authentication"
        patterns:
          - "(javax|jakarta)\\.security\\.(auth\\.message|jacc)\\..*"

      - name: "Security Layers"
        patterns:
          - "jakarta\\.security\\..*"
          - "javax\\.security\\..*"


  - name: "Observability & Reliability"
    subcategories:

      - name: "Metrics & Distributed Tracing"
        patterns:
          - "jakarta\\.metrics\\..*"

  - name: "Development & Testing Tools"
    subcategories:

      - name: "Build Tools & Dependency Management"
        patterns:
          - "javax\\.annotation\\..*"
          - "jakarta\\.annotation\\..*"


