categories:
  - name: "Messaging & Data Integration"
    subcategories:

      - name: "Message Brokers & ETL Tools"
        patterns:
          - "org\\.apache\\.activemq.*"
          - "org\\.apache\\.camel.*"
          - "com\\.ibm\\.(mq|wmq).*"
          - "com\\.atomikos.*"
          - "com\\.rabbitmq.*"
          - "com\\.solacesystems.*"
          - "io\\.projectreactor\\.rabbitmq.*"
          - "org\\.eclipse\\.paho.*"
          - "org\\.messaginghub.*"
          - "org\\.synchronoss\\.cloud.*"

      - name: "API Gateways & REST/GraphQL"
        patterns:
          - "io\\.micronaut:micronaut-(grpc|jaxrs|openapi)"
          - "(javax|jakarta)\\.ws\\.rs(\\..*)?"
          - "(javax|jakarta)\\.xml\\.ws(\\..*)?"
          - "com\\.google\\.api.*"
          - "com\\.google\\.http-client.*"
          - "org\\.apache\\.cxf.*"
          - "org\\.apache\\.httpcomponents.*"
          - "org\\.apache\\.ws.*"
          - "com\\.graphql-java.*"
          - "com\\.github\\.tomakehurst.*"
          - "com\\.netflix\\.eureka.*"
          - "com\\.netflix\\.ribbon.*"
          - "com\\.squareup\\.okhttp3.*"
          - "com\\.sun\\.jersey.*"
          - "io\\.grpc.*"
          - "io\\.github\\.openfeign.*"
          - "io\\.rsocket.*"
          - "io\\.rest-assured.*"
          - "io\\.springfox.*"
          - "io\\.swagger\\.core.*"

      - name: "Event Streaming"
        patterns:
          - "org\\.apache\\.kafka.*"
          - "org\\.apache\\.pulsar.*"
          - "io\\.projectreactor\\.kafka.*"

      - name: "Networking"
        patterns:
          - "io\\.netty.*"
          - "io\\.projectreactor\\.netty.*"
          - "com\\.jcraft.*"
          - "org\\.tmatesoft.*"
