categories:
  - name: "Infrastructure & Deployment"
    subcategories:
      - name: "Containerization & Orchestration"
        patterns: []
      - name: "Cloud Platforms"
        patterns:
          - "^micronaut-discovery$"
      - name: "Application Servers"
        patterns:
          - "^micronaut-http-(server|simple|netty)$"
          - "^micronaut-runtime$"

  - name: "Data Management & Storage"
    subcategories:
      - name: "Relational Databases"
        patterns:
          - "^micronaut-data-(jdbc|jpa|r2dbc|hibernate)$"
      - name: "NoSQL & Big Data"
        patterns:
          - "^micronaut-data-(mongodb|cosmos)$"
      - name: "Data Access Core"
        patterns:
          - "^micronaut-data-(annotation|connection|model|operations|repository)$"
      - name: "Data Operations & Internals"
        patterns:
          - "^micronaut-data-(event|exceptions|intercept|processor|document)$"
      - name: "Caching"
        patterns: []
      - name: "Data Lakes & Analytics"
        patterns: []

  - name: "Messaging & Data Integration"
    subcategories:
      - name: "Message Brokers & ETL Tools"
        patterns:
          - "^micronaut-messaging$"
      - name: "API Gateways & REST/GraphQL"
        patterns:
          - "^micronaut-http(-[a-z]+)?$"
      - name: "Event Streaming"
        patterns: []
      - name: "Networking"
        patterns:
          - "^micronaut-buffer-netty$"

  - name: "Application Development"
    subcategories:
      - name: "Web Frameworks"
        patterns:
          - "^micronaut-web-router$"
          - "^micronaut-websocket$"
          - "^micronaut-function$"
      - name: "Spring: Boot"
        patterns: []
      - name: "Spring: Framework"
        patterns: []
      - name: "Reactive Libraries"
        patterns:
          - "^micronaut-http-reactive$"
      - name: "Dependency Injection"
        patterns:
          - "^micronaut-context$"
          - "^micronaut-inject$"
          - "^micronaut-aop$"
      - name: "Template Engines"
        patterns: []

  - name: "Serialization"
    subcategories:
      - name: "JSON/XML"
        patterns:
          - "^micronaut-j(ackson|son)$"
      - name: "Protocol Buffers & Binary Formats"
        patterns: []

  - name: "Security & Identity"
    subcategories:
      - name: "Authentication"
        patterns: []
      - name: "Security Layers"
        patterns: []
      - name: "Transport & Data Security"
        patterns: []
      - name: "Identity Management"
        patterns: []

  - name: "Observability & Reliability"
    subcategories:
      - name: "Logging & Monitoring"
        patterns:
          - "^micronaut-logging$"
          - "^micronaut-management-(endpoint|health)$"
          - "^micronaut-health$"
      - name: "Metrics & Distributed Tracing"
        patterns: []
      - name: "Circuit Breakers & Rate Limiting"
        patterns: []

  - name: "Development & Testing Tools"
    subcategories:
      - name: "Build Tools & Dependency Management"
        patterns:
          - "^micronaut-annotation-processing$"
          - "^micronaut-ast-groovy$"
      - name: "Testing"
        patterns:
          - "^micronaut-http-tck$"
          - "^micronaut-testsuitehelper$"
      - name: "Code Quality & Profiling"
        patterns: []

  - name: "Utilities & Libraries"
    subcategories:
      - name: "General-Purpose"
        patterns:
          - "^micronaut-core-[a-z-]+$"
          - "^micronaut-(docs-expressions|expressions|graal-reflect|retry|scheduling|validation)$"
