categories:
  - name: "Infrastructure & Deployment"
    subcategories:
      - name: "Containerization & Orchestration"
        patterns:
          - "^io\\.micronaut\\.kubernetes:.*"
          - "^io\\.micronaut\\.testresources:.*testcontainers$"
      - name: "Cloud Platforms"
        patterns:
          - "^io\\.micronaut\\.aws:.*"
          - "^io\\.micronaut\\.gcp:.*"
          - "^io\\.micronaut\\.azure:.*"
          - "^io\\.micronaut\\.oraclecloud:.*"
      - name: "Application Servers"
        patterns:
          - "^io\\.micronaut:micronaut-http-(server|netty).*"
          - "^io\\.micronaut:micronaut-runtime.*"
          - "^io\\.micronaut\\.servlet:.*"

  - name: "Data Management & Storage"
    subcategories:
      - name: "Relational Databases"
        patterns:
          - "^io\\.micronaut\\.data:.*(jdbc|jpa|r2dbc|hibernate|spring-jpa).*"
          - "^io\\.micronaut\\.sql:micronaut-jdbc-.*"
          - "^io\\.micronaut\\.jasync:.*"
      - name: "NoSQL & Big Data"
        patterns:
          - "^io\\.micronaut\\.data:.*(mongodb|cosmos|redis).*"
          - "^io\\.micronaut\\.mongodb:.*"
          - "^io\\.micronaut\\.redis:.*"
          - "^io\\.micronaut\\.cassandra:.*"
      - name: "Caching"
        patterns:
          - "^io\\.micronaut\\.cache:.*"
          - "^io\\.micronaut\\.microstream:.*"

  - name: "Messaging & Data Integration"
    subcategories:
      - name: "Message Brokers"
        patterns:
          - "^io\\.micronaut\\.kafka:.*"
          - "^io\\.micronaut\\.rabbitmq:.*"
          - "^io\\.micronaut\\.nats:.*"
          - "^io\\.micronaut\\.pulsar:.*"
          - "^io\\.micronaut\\.mqtt:.*"
      - name: "API Gateways & REST/GraphQL"
        patterns:
          - "^io\\.micronaut:micronaut-http.*"
          - "^io\\.micronaut\\.graphql:.*"

  - name: "Application Development"
    subcategories:
      - name: "Dependency Injection"
        patterns:
          - "^io\\.micronaut:micronaut-(inject|context|aop).*"
          - "^io\\.micronaut\\.guice:.*"
      - name: "Web Frameworks"
        patterns:
          - "^io\\.micronaut:micronaut-(websocket|router|views).*"
      - name: "Template Engines"
        patterns:
          - "^io\\.micronaut\\.views:.*(thymeleaf|freemarker|handlebars|pebble).*"

  - name: "Security & Identity"
    subcategories:
      - name: "Authentication"
        patterns:
          - "^io\\.micronaut\\.security:.*(jwt|oauth2|ldap).*"
      - name: "Security Tooling"
        patterns:
          - "^io\\.micronaut\\.security:.*session.*"
          - "^io\\.micronaut\\.vault:.*"

  - name: "Observability & Reliability"
    subcategories:
      - name: "Metrics & Tracing"
        patterns:
          - "^io\\.micronaut\\.micrometer:.*"
          - "^io\\.micronaut\\.tracing:.*"
      - name: "Logging"
        patterns:
          - "^io\\.micronaut\\.logging:.*"

  - name: "Development & Testing Tools"
    subcategories:
      - name: "Testing"
        patterns:
          - ".*:.*(-tck|-test)$"
          - "^io\\.micronaut\\.test:.*"
      - name: "Build Tools"
        patterns:
          - "^io\\.micronaut\\.build:.*"
          - "^io\\.micronaut\\.gradle:.*"

  - name: "Utilities & Libraries"
    subcategories:
      - name: "Core Utilities"
        patterns:
          - "^io\\.micronaut:micronaut-(core|validation|retry).*"
      - name: "Specialized Libraries"
        patterns:
          - "^io\\.micronaut\\.email:.*"
          - "^io\\.micronaut\\.langchain4j:.*"
          - "^io\\.micronaut\\.objectstorage:.*"