categories:

  - name: "Infrastructure & Deployment"
    subcategories:
      - name: "Containerization & Orchestration"
        patterns:
          - "io\\.micronaut\\.kubernetes:micronaut-kubernetes.*"

      - name: "Cloud Platforms"
        patterns:
          - "io\\.micronaut\\.(aws|azure|gcp|oraclecloud):micronaut-.*"

      - name: "Virtualization & Hypervisors"
        patterns: []

      - name: "Service Discovery"
        patterns:
          - "io\\.micronaut\\.discovery.*"

      - name: "Platform Management"
        patterns:
          - "io\\.micronaut\\.platform.*"

      - name: "Checkpoint & Restore"
        patterns:
          - "io\\.micronaut\\.crac.*"

  - name: "Data Management & Storage"
    subcategories:
      - name: "Relational Databases"
        patterns:
          - "io\\.micronaut\\.(sql|jdbc|data|r2dbc):micronaut-.*"
          - "io\\.micronaut\\.flyway:micronaut-flyway.*"
          - "io\\.micronaut\\.liquibase:micronaut-liquibase.*"
          - "io\\.micronaut\\.neo4j.*"

      - name: "NoSQL & Big Data"
        patterns:
          - "io\\.micronaut\\.(mongodb|cassandra|redis|opensearch|microstream):micronaut-.*"

      - name: "Caching"
        patterns:
          - "io\\.micronaut\\.cache:micronaut-cache.*"
          - "io\\.micronaut\\.redis:micronaut-redis-lettuce.*"
          - "io\\.micronaut\\.coherence.*"

      - name: "File & Storage Utilities"
        patterns:
          - "io\\.micronaut\\.core\\.io.*"
          - "io\\.micronaut\\.eclipsestore.*"
          - "io\\.micronaut\\.objectstore.*"

  - name: "Messaging & Data Integration"
    subcategories:
      - name: "Message Brokers & ETL Tools"
        patterns:
          - "io\\.micronaut\\.(kafka|rabbitmq|mqtt|nats|pulsar|jms):micronaut-.*"

      - name: "API Gateways & REST/GraphQL"
        patterns:
          - "io\\.micronaut\\.(http-client|grpc|openapi|graphql):micronaut-.*"

      - name: "Event Streaming"
        patterns:
          - "io\\.micronaut\\.kafka:micronaut-kafka-streams.*"

      - name: "Networking"
        patterns:
          - "io\\.micronaut\\.netty.*"
          - "io\\.micronaut\\.websocket.*"

  - name: "Application Development"
    subcategories:
      - name: "Web Frameworks"
        patterns:
          - "io\\.micronaut:micronaut-http-server.*"
          - "io\\.micronaut\\.http.server.*"
          - "io\\.micronaut\\.servlet.*"
          - "io\\.micronaut\\.jaxrs.*"

      - name: "Reactive Libraries"
        patterns:
          - "io\\.micronaut\\.reactor:micronaut-reactor.*"
          - "io\\.micronaut\\.rxjava:micronaut-rxjava.*"
          - "io\\.micronaut\\.rxjava2.*"

      - name: "Dependency Injection"
        patterns:
          - "io\\.micronaut:micronaut-inject.*"
          - "io\\.micronaut\\.inject.*"
          - "io\\.micronaut\\.spring.*"
          - "io\\.micronaut\\.guice.*"

      - name: "Template Engines"
        patterns:
          - "io\\.micronaut\\.thymeleaf:micronaut-thymeleaf.*"
          - "io\\.micronaut\\.views:micronaut-views.*"

      - name: "Expression Language"
        patterns:
          - "io\\.micronaut\\.expressions.*"

  - name: "Serialization"
    subcategories:
      - name: "JSON/XML"
        patterns:
          - "io\\.micronaut\\.serde:micronaut-serde.*"
          - "io\\.micronaut\\.jackson:micronaut-jackson.*"
          - "io\\.micronaut\\.json.*"
          - "io\\.micronaut\\.xml.*"
          - "io\\.micronaut\\.toml.*"

      - name: "Protocol Buffers & Binary Formats"
        patterns:
          - "io\\.micronaut\\.protobuf:micronaut-protobuf.*"

  - name: "Security & Identity"
    subcategories:
      - name: "Authentication"
        patterns:
          - "io\\.micronaut\\.security:micronaut-security-(jwt|oauth2|ldap).*"

      - name: "Security Layers"
        patterns:
          - "io\\.micronaut\\.security:micronaut-security.*"
          - "io\\.micronaut\\.multitenancy.*"

      - name: "Transport & Data Security"
        patterns:
          - "io\\.micronaut\\.ssl:micronaut-ssl.*"
          - "io\\.micronaut\\.http.ssl.*"

  - name: "Observability & Reliability"
    subcategories:
      - name: "Logging & Monitoring"
        patterns:
          - "io\\.micronaut\\.logging:micronaut-logging.*"
          - "io\\.micronaut\\.management\\.health.*"
          - "io\\.micronaut\\.controlpanel.*"
          - "io\\.micronaut\\.netflix.*"

  - name: "Development & Testing Tools"
    subcategories:
      - name: "Build Tools & Dependency Management"
        patterns:
          - "io\\.micronaut\\.gradle:micronaut-gradle-plugin.*"
          - "io\\.micronaut\\.maven.*"

      - name: "Testing (Unit, Integration, Performance)"
        patterns:
          - "io\\.micronaut\\.test:micronaut-test-.*"
          - "io\\.micronaut\\.testresources:micronaut-test-resources.*"
          - "io\\.micronaut\\.validation.*"

  - name: "Utilities & Libraries"
    subcategories:
      - name: "General-Purpose"
        patterns:
          - "io\\.micronaut\\.picocli.*"
          - "io\\.micronaut\\.sourcegen.*"
          - "io\\.micronaut\\.Session.*"
          - "io\\.micronaut\\.langchain4j.*"

