categories:
  - name: "Utilities & Libraries"
    subcategories:

      - name: "General Purpose"
        patterns:
          - "io\\.micronaut:micronaut-(serde|groovy|kotlin)"
          - "(javax|jakarta)\\.activation(\\..*)?"
          - "(javax|jakarta)\\.annotation(\\..*)?"
          - "(javax|jakarta)\\.inject(\\..*)?"
          - "(javax|jakarta)\\.mail(\\..*)?"
          - "(javax|jakarta)\\.management\\.j2ee(\\..*)?"
          - "com\\.google\\.guava.*"
          - "com\\.google\\.code.*"
          - "org\\.apache\\.commons.*"
          - "org\\.apache\\.groovy.*"
          - "org\\.apache\\.poi.*"
          - "cglib.*"
          - "com\\.jcraft.*"
          - "com\\.github\\.ben-manes.*"
          - "com\\.github\\.fge.*"
          - "com\\.sun\\.(xml|activation|mail).*"
          - "commons-(beanutils|codec|fileupload|lang).*"
          - "com\\.samskivert.*"
          - "com\\.sendgrid.*"
          - "com\\.sun\\.mail.*"
          - "info\\.picocli.*"
          - "dev\\.langchain4j.*"
          - "dev\\.miku.*"
          - "cryptomatric.*"
          - "joda-time.*"
          - "net\\.bytebuddy.*"
          - "loaniq\\.lib.*"
          - "me\\.snowdrop.*"
          - "org\\.bouncycastle.*"
          - "org\\.drools.*"
          - "nz\\.net\\.ultrag.*"
          - "org\\.jetbrains\\.kotlin.*"
          - "org\\.javassist.*"
          - "org\\.jsoup.*"
          - "org\\.jobkia.*"
          - "org\\.mapstruct.*"
          - "org\\.optaplanner.*"
          - "org\\.osgi.*"
          - "org\\.quartz-scheduler.*"
          - "org\\.objenesis.*"
          - "org\\.ow2\\.asm.*"
          - "org\\.skyscreamer.*"
          - "org\\.webjars.*"
          - "org\\.tmatesoft.*"
          - "org\\.projectionhok.*"

      - name: "Networking"
        patterns:
          - "io\\.netty.*"
          - "io\\.projectreactor\\.netty.*"
