categories:

  - name: "Web & Application Frameworks"
    subcategories:

      - name: "Spring: Boot"
        patterns:
          - "^org\\.springframework\\.boot.*"
          - "^spring-boot-starter(-[a-z0-9-]+)?$"
          - "^spring-boot-autoconfigure$"
          - "^spring-boot-actuator(-autoconfigure)?$"
          - "^spring-boot-configuration-processor$"
          - "^spring-boot-devtools$"
          - "^spring-boot-test(-autoconfigure)?$"
          - "^spring-boot-loader$"
          - "^spring-boot-properties-migrator$"

      - name: "Spring: Framework"
        patterns:
          - "^spring-aop$"
          - "^spring-aspects$"
          - "^spring-beans$"
          - "^spring-context(-indexer|-support)?$"
          - "^spring-core(-test)?$"
          - "^spring-expression$"
          - "^spring-instrument$"
          - "^spring-jdbc$"
          - "^spring-jms$"
          - "^spring-messaging$"
          - "^spring-orm$"
          - "^spring-oxm$"
          - "^spring-r2dbc$"
          - "^spring-test$"
          - "^spring-tx$"
          - "^spring-web$"
          - "^spring-webflux$"
          - "^spring-webmvc$"
          - "^spring-websocket$"
          - "^org\\.springframework:spring-[a-z0-9-]+$"

