categories:
  - name: "Application Development"
    subcategories:
      - name: "Runtime Containers & Servers"
        patterns:
          - "io\\.micronaut:micronaut-servlet"
          - "javax\\.servlet(\\..*)?"  # Servlet API (e.g., javax.servlet.Filter)
      - name: "Web Frameworks (Full-Stack, Micro, Reactive)"
        patterns:
          - "io\\.micronaut:micronaut-(views|reactor)"
          - "javax\\.websocket(\\..*)?"  # WebSocket API (e.g., javax.websocket.Endpoint)