categories:
  - name: "Security & Identity"
    subcategories:

      - name: "Authentication"
        patterns:
          - "com\\.google\\.auth.*"
          - "com\\.nimbusds.*"
          - "com\\.unboundid.*"
          - "org\\.crac.*"
          - "^org\\.opensaml:.*"

      - name: "Security Layers"
        patterns:
          - "org\\.owasp\\..*"

      - name: "Transport & Data Security"
        patterns:
          - "org\\.jasypt.*"

      - name: "Identity Management (SSO, RBAC)"
        patterns: []
