categories:

  - name: "Infrastructure & Deployment"
    subcategories:

      - name: "Containerization & Orchestration"
        patterns:
          - "org\\.springframework\\.cloud\\.kubernetes.*"
          - "org\\.springframework\\.boot\\.docker.*"

      - name: "Cloud Platforms"
        patterns:
          - "org\\.springframework\\.cloud\\.(aws|azure|gcp).*"
          - "org\\.springframework\\.cloud\\.config.*"

      - name: "Application Servers"
        patterns:
          - "org\\.springframework\\.boot\\.(tomcat|jetty|undertow).*"

  - name: "Data Management & Storage"
    subcategories:

      - name: "Relational Databases"
        patterns:
          - "org\\.springframework\\.data:spring-data-(jpa|jdbc|r2dbc|relational).*"
          - "org\\.springframework:spring-(jdbc|orm|tx|r2dbc).*"

      - name: "NoSQL & Big Data"
        patterns:
          - "org\\.springframework\\.data:spring-data-(cassandra|couchbase|elasticsearch|envers|gemfire|geode|keyvalue|ldap|mongodb|neo4j|redis|solr).*"

      - name: "Caching"
        patterns:
          - "org\\.springframework\\.cache.*"

  - name: "Messaging & Data Integration"
    subcategories:

      - name: "Message Brokers & ETL Tools"
        patterns:
          - "org\\.springframework\\.(amqp|jms|kafka|integration|batch):.*"
          - "org\\.springframework\\.(ldap|pulsar):.*"
          - "org\\.springframework:spring-(jms|messaging).*"

      - name: "API Gateways & REST/GraphQL"
        patterns:
          - "org\\.springframework\\.web\\.(rest|servlet|mvc).*"
          - "org\\.springframework\\.graphql.*"
          - "org\\.springframework\\.data:spring-data-rest-.*"
          - "org\\.springframework\\.hateoas:spring-hateoas.*"
          - "org\\.springframework\\.restdocs:spring-restdocs-.*"
          - "org\\.springframework\\.ws:spring-ws-.*"

      - name: "Event Streaming"
        patterns:
          - "org\\.springframework\\.cloud\\.stream.*"

      - name: "Networking"
        patterns:
          - "org\\.springframework\\.web\\.(client|socket).*"
          - "org\\.springframework\\.web\\.socket.*"

  - name: "Application Development"
    subcategories:

      - name: "Web Frameworks"
        patterns:
          - "org\\.springframework:spring-(web|webmvc|webflux|websocket).*"

      - name: "Spring: Boot"
        patterns:
          - "org\\.springframework\\.boot.*"

      - name: "Spring: Framework"
        patterns:
          - "org\\.springframework:spring-(core|beans|context|aop|expression|instrument|jcl|aspects).*"

      - name: "Reactive Libraries"
        patterns:
          - "org\\.springframework\\.web\\.reactive.*"
          - "io\\.projectreactor.*"

      - name: "Dependency Injection"
        patterns:
          - "org\\.springframework\\.(beans|context).*"

      - name: "Template Engines"
        patterns:
          - "org\\.springframework\\.web\\.servlet\\.view.*"
          - "org\\.thymeleaf.*"


  - name: "Serialization"
    subcategories:
      - name: "JSON/XML"
        patterns:
          - "org\\.springframework\\.http\\.converter\\.(json|xml).*"
          - "org\\.springframework:spring-(oxm).*"
          - "org\\.springframework\\.ws:spring-xml.*"

      - name: "Protocol Buffers & Binary Formats"
        patterns: []

  - name: "Security & Identity"
    subcategories:
      - name: "Authentication"
        patterns:
          - "org\\.springframework\\.security:spring-security-(oauth2|saml2|openid|cas|ldap|remoting|rsocket).*"

      - name: "Security Layers"
        patterns:
          - "org\\.springframework\\.security:spring-security-(acl|config|core|crypto|data|messaging|taglibs|test|web).*"
          - "org\\.springframework\\.credhub:spring-credhub-core.*"
          - "org\\.springframework\\.security:spring-security-aspects.*"

      - name: "Transport & Data Security"
        patterns:
          - "org\\.springframework\\.security\\.(ssl|headers).*"
          - "org\\.springframework\\.vault:spring-vault-core.*"
          - "org\\.springframework\\.security:spring-security-rsa.*"
      - name: "Identity Management"
        patterns:
          - "org\\.springframework\\.security\\.(ldap|saml).*"

  - name: "Observability & Reliability"
    subcategories:
      - name: "Logging & Monitoring"
        patterns:
          - "org\\.springframework\\.boot\\.actuate.*"
      - name: "Metrics & Distributed Tracing"
        patterns:
          - "io\\.micrometer\\.spring.*"
          - "org\\.springframework\\.cloud\\.sleuth.*"
      - name: "Circuit Breakers & Rate Limiting"
        patterns:
          - "org\\.springframework\\.cloud\\.(circuitbreaker|resilience4j).*"
          - "org\\.springframework\\.retry.*"

  - name: "Development & Testing Tools"
    subcategories:

      - name: "Build Tools & Dependency Management"
        patterns:
          - "org\\.springframework\\.boot\\.(gradle|maven).*"

      - name: "Testing"
        patterns:
          - "org\\.springframework:spring-test.*"
          - "org\\.springframework:spring-mock.*"

      - name: "Code Quality & Profiling"
        patterns: []

  - name: "Utilities & Libraries"
    subcategories:
      - name: "Functional/Reactive Libraries"
        patterns: []

      - name: "General Purpose"
        patterns:
          - "org\\.springframework\\.util.*"
          - "org\\.springframework\\.session.*"
          - "org\\.springframework\\.plugin:spring-plugin-.*"
          - "org\\.springframework\\.data:spring-data-commons.*"

